# Generated by Django 2.1 on 2019-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20190815_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(max_length=45),
        ),
    ]
