# Generated by Django 2.1 on 2019-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20190815_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='copias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='fechadecompra',
            field=models.DateField(verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaprestamo',
            field=models.DateField(verbose_name='Fecha de prestamo'),
        ),
    ]
