# Generated by Django 2.1 on 2019-08-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_auto_20190815_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamo',
            name='fechadedevolucion',
            field=models.DateField(null=True, verbose_name='fecha de devolucion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(verbose_name='actualmente posee el libro'),
        ),
    ]
